name: ExoPlayer FFmpeg Extension

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@16cca5479d7c6b6843f6a6515640ba33c6501543 # tag=v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build ffmpeg
        run: ./build.sh
      - name: Force specific version of cmake to build extension
        run: |
          cmake=(${ANDROID_SDK_ROOT}/cmake/3.10.2*)
          echo cmake.dir="${cmake[0]}" | tee -a local.properties
      - name: Build aar extension
        run: ./gradlew assembleRelease
      - name: Upload aar
        uses: actions/upload-artifact@v2
        with:
          name: upload-exoplayer-ffmpeg 
          path: "ExoPlayer/extensions/ffmpeg/build/outputs/"
